package cn.freeteam.cms.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

public class Info implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String id;
    private String state;
    private String issign;
    private String iscomment;
    private String iscommentStr;
    public static String ISCOMMENT_NO="0";//不允许评论
    public static String ISCOMMENT_MEMBER="1";//会员评论
    public static String ISCOMMENT_ALL="2";//会员和匿名评论
    private String video;
    private List<String> channelids;//查询条件 栏目集合
    private String checkOpenendtime;//查询条件 检查公开时限
    private String addUserLoginName;
    private String addUserName;
    private int countnum;
    private String datename;
    private int htmlIndexnum;
    private String htmlFileName;//生成的html文件名
    private String isimgs;
    
 
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.site
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String site;
    private String infosite;
    private String sitename;
    private String indexnum;
    private String opentype;
    private String opentimetype;
    private Date openendtime;
    private String openendtimeSec;
    private String openendtimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.channel
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String channel;
    private String channelname;
    private String channelPagemark;
    private int channelIndexnum;
    private String channelFolder;
    private String channelParid;
    private String channelParPagemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.title
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.shortTitle
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String shorttitle;
    private String showtitle;//列表显示的标题
    private int showtitleLen;//列表显示的标题长度
    private String showtitleMark;//列表显示的标题长度超过限制后显示的字符
    private String pageurl;//本信息的链接地址
    private String noids;
    private String sitepath;
    private String[] channels;
    private Date starttime;
    private Date endtime;
    private Date infostarttime;
    private Date infoendtime;
    private String infostarttimeStr;
    private String infoendtimeStr;

    private Date infostarttimeNoeq;
    private Date infoendtimeNoeq;
    private String infostarttimeNoeqStr;
    private String infoendtimeNoeqStr;
    
    private int infoStartClicknum;
    private int infoEndClicknum;
    private String searchKey;
    private String ishot;//是否热点
    private String isnew;//是否最新

    /**
     * update by limengyu 2013.09.29  
     */
    private String ischeck;	//是否审核1为审核，默认为0
    private String editor;	//编辑
    private String keywords; // 关键词
    private int firstvalue; //优先值  
    private String isshowindex; //是否在首页显示，1为显示0为不显示，默认为1
    private String isshowlist;//是否在列表页显示，1为显示0为不显示，默认为1
    private String isrecommend; //是否推荐，1为推荐，0为不推荐，默认为1
    
    private String isnotinid; //infoList标签用，表中不存在
    private String way; //InfoSearch标签用，表中不存在，0为全文检索，1为标题检索\
    private String scope;//InfoList标签用，表中不存在
    
    private String modifier; //修改人
    private Date mdtime;	//修改时间
    
    private String isshownewscenter; //是否在新闻中心显示
    
    private String istopnewscenter; //是否在新闻中心置顶
    
    private String isrecommendnewscenter; //是否在新闻中心推荐
    
    private int isquote;	//是否为引用文章
    
    private String quoteinfoid;
    
    
    private String recommendreason;	//推荐理由
    private String suitage;			//适读年龄
    private String depth;			//深度
    
    
	public String getRecommendreason() {
		return recommendreason;
	}

	public void setRecommendreason(String recommendreason) {
		this.recommendreason = recommendreason;
	}

	public String getSuitage() {
		return suitage;
	}

	public void setSuitage(String suitage) {
		this.suitage = suitage;
	}

	public String getDepth() {
		return depth;
	}

	public void setDepth(String depth) {
		this.depth = depth;
	}
	/**
     * 防止外链把pageurl覆盖，数据库不存在该字段
     * 默认为 infourl=/details/年份/htmlindex.shtml
     */
    private String infourl;
    public String getInfourl() {
    	//防止被外链覆盖，扩展字段
    	infourl="/details/"+(getAddtime().getYear()+1900)+"/"+getHtmlFileName()+".shtml";
		return infourl;
	}
    /**
     * 青年建筑师扩展字段
     * gzlm 关注栏目
     * bjyx 编辑邮箱
     * nper	期数，第几期
     */
    private String gzlm;
    private String bjyx;
    private int nper;
    
	public String getGzlm() {
		return gzlm;
	}

	public void setGzlm(String gzlm) {
		this.gzlm = gzlm;
	}

	public String getBjyx() {
		return bjyx;
	}

	public void setBjyx(String bjyx) {
		this.bjyx = bjyx;
	}

	public int getNper() {
		return nper;
	}

	public void setNper(int nper) {
		this.nper = nper;
	}

	public void setInfourl(String infourl) {
		this.infourl = infourl;
	}
    
	public String getScope() {
		return scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	public String getWay() {
		return way;
	}

	public void setWay(String way) {
		this.way = way;
	}

	public String getIsnotinid() {
		return isnotinid;
	}

	public void setIsnotinid(String isnotinid) {
		this.isnotinid = isnotinid;
	}

	public String getIsrecommend() {
		return isrecommend;
	}

	public void setIsrecommend(String isrecommend) {
		this.isrecommend = isrecommend;
	}

	public String getIsshowindex() {
		return isshowindex;
	}

	public void setIsshowindex(String isshowindex) {
		this.isshowindex = isshowindex;
	}

	public String getIsshowlist() {
		return isshowlist;
	}

	public void setIsshowlist(String isshowlist) {
		this.isshowlist = isshowlist;
	}

	public int getFirstvalue() {
		return firstvalue;
	}

	public void setFirstvalue(int firstvalue) {
		this.firstvalue = firstvalue;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.titleColor
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String titlecolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.titleBlod
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String titleblod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.source
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.author
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String author;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.description
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.tags
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.img
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.url
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.attchs
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String attchs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.addtime
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private Date addtime;
    private String addtimeStr;
    private String dateFormat;
    private String addtimeBetween;//day、week、month、year

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.templet
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String templet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.isTop
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String istop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.topEndTime
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private Date topendtime;
    private String topendtimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.clickNum
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private Integer clicknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.addUser
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String adduser;
    private String adduserLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.content
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.site
     *
     * @return the value of info.site
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.site
     *
     * @param site the value for info.site
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.channel
     *
     * @return the value of info.channel
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.channel
     *
     * @param channel the value for info.channel
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.title
     *
     * @return the value of info.title
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.title
     *
     * @param title the value for info.title
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.shortTitle
     *
     * @return the value of info.shortTitle
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getShorttitle() {
    	if (showtitleLen>0) {
			if (StringUtils.isEmpty(shorttitle)) {
				shorttitle=title;
			}
			if (shorttitle.length()>showtitleLen) {
				shorttitle=cutString(shorttitle, showtitleLen, showtitleMark);
			}
		}
        return shorttitle;
    }
 
    public String cutString(String str, int len, String mark) {

        int markCounter = 0;
        if(StringUtils.isBlank(mark)){
        	mark = "";
        }
        for (int i = 0; i < mark.length(); i++) {
            char c = mark.charAt(i);
            if (c < 255 && c != '（' && c != '）') {
                markCounter++;
            } else {
                markCounter = markCounter + 2;
            }
        }

        len = len * 2;
        String strs = "";
        int strCounter = 0;
        int endCutString = 0;
        boolean isMark = false;
        List<Map<Integer, Integer>> cutLenList = new ArrayList<Map<Integer, Integer>>();
        List<Map<Integer, String>> strList = new ArrayList<Map<Integer, String>>();
        for (int i = 0; i < str.length(); i++) {
            
            char c = str.charAt(i);            
            if (c < 255 && c != '（' && c != '）') {
                strCounter++;
            } else {
                strCounter = strCounter + 2;
            }
            
            Map<Integer, Integer> cutLenMap = new HashMap<Integer, Integer>();
            Map<Integer, String> strMap = new HashMap<Integer, String>();
            cutLenMap.put(i, strCounter);
            cutLenList.add(cutLenMap);
            strMap.put(i, strs += c);
            strList.add(strMap);
            
            if (strCounter > len) {
                isMark = true;
                if((strCounter + markCounter) > len){
                    for(int k=i; k>=0; k--){
                        Map<Integer, Integer> m = cutLenList.get(k);
                        int l = 0;
                        l = m.get(k);
                        if((l + markCounter) < len){
                            endCutString = k;
                            break;
                        }
                    }
                }else{
                    endCutString = i;
                }
            }else{
                endCutString = i;
            }
            
        }
        
        if(strList.size() > endCutString && isMark == true){
            str = strList.get(endCutString).get(endCutString) + mark;
        }

        return str;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.shortTitle
     *
     * @param shorttitle the value for info.shortTitle
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setShorttitle(String shorttitle) {
        this.shorttitle = shorttitle == null ? null : shorttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.titleColor
     *
     * @return the value of info.titleColor
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getTitlecolor() {
        return titlecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.titleColor
     *
     * @param titlecolor the value for info.titleColor
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setTitlecolor(String titlecolor) {
        this.titlecolor = titlecolor == null ? null : titlecolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.titleBlod
     *
     * @return the value of info.titleBlod
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getTitleblod() {
        return titleblod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.titleBlod
     *
     * @param titleblod the value for info.titleBlod
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setTitleblod(String titleblod) {
        this.titleblod = titleblod == null ? null : titleblod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.source
     *
     * @return the value of info.source
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.source
     *
     * @param source the value for info.source
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.author
     *
     * @return the value of info.author
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.author
     *
     * @param author the value for info.author
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.description
     *
     * @return the value of info.description
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.description
     *
     * @param description the value for info.description
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.tags
     *
     * @return the value of info.tags
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.tags
     *
     * @param tags the value for info.tags
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.img
     *
     * @return the value of info.img
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.img
     *
     * @param img the value for info.img
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.url
     *
     * @return the value of info.url
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.url
     *
     * @param url the value for info.url
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.attchs
     *
     * @return the value of info.attchs
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getAttchs() {
        return attchs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.attchs
     *
     * @param attchs the value for info.attchs
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setAttchs(String attchs) {
        this.attchs = attchs == null ? null : attchs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.addtime
     *
     * @return the value of info.addtime
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.addtime
     *
     * @param addtime the value for info.addtime
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.templet
     *
     * @return the value of info.templet
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getTemplet() {
        return templet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.templet
     *
     * @param templet the value for info.templet
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setTemplet(String templet) {
        this.templet = templet == null ? null : templet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.isTop
     *
     * @return the value of info.isTop
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.isTop
     *
     * @param istop the value for info.isTop
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setIstop(String istop) {
        this.istop = istop == null ? null : istop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.topEndTime
     *
     * @return the value of info.topEndTime
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public Date getTopendtime() {
        return topendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.topEndTime
     *
     * @param topendtime the value for info.topEndTime
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setTopendtime(Date topendtime) {
        this.topendtime = topendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.clickNum
     *
     * @return the value of info.clickNum
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public Integer getClicknum() {
        return clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.clickNum
     *
     * @param clicknum the value for info.clickNum
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setClicknum(Integer clicknum) {
        this.clicknum = clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.addUser
     *
     * @return the value of info.addUser
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.addUser
     *
     * @param adduser the value for info.addUser
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser == null ? null : adduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.content
     *
     * @return the value of info.content
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.content
     *
     * @param content the value for info.content
     *
     * @mbggenerated Wed Feb 01 16:28:18 CST 2012
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	public String getAddtimeStr() {
		if (dateFormat==null || dateFormat.trim().length()==0) {
			dateFormat="yyyy-MM-dd HH:mm:ss";
		}
		if (addtime!=null) {
			addtimeStr=new SimpleDateFormat(dateFormat).format(addtime);
		}
		return addtimeStr;
	}

	public void setAddtimeStr(String addtimeStr) {
		this.addtimeStr = addtimeStr;
	}

	public String getTopendtimeStr() {
		if (topendtime!=null) {
			topendtimeStr=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(topendtime);
		}
		return topendtimeStr;
	}

	public void setTopendtimeStr(String topendtimeStr) {
		this.topendtimeStr = topendtimeStr;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getShowtitle() {
		if (StringUtils.isEmpty(showtitle)) {
			//默认为标题
			showtitle=this.title;
			//判断是否有短标题
			if (shorttitle!=null && shorttitle.trim().length()>0) {
				showtitle=shorttitle;
			}
			//判断标题长度
			if (showtitleLen>0 && showtitle.length()>showtitleLen) {
				showtitle=cutString(showtitle, showtitleLen, showtitleMark);
			}
			//添加标题颜色
			//showtitle="<font color='"+titlecolor+"'>"+showtitle+"</font>";
			//判断是否粗体
			if ("1".equals(titleblod)) {
				showtitle="<b>"+showtitle+"</b>";
			}
		}
		return showtitle;
	}

	public void setShowtitle(String showtitle) {
		this.showtitle = showtitle;
	}

	public int getShowtitleLen() {
		return showtitleLen;
	}

	public void setShowtitleLen(int showtitleLen) {
		this.showtitleLen = showtitleLen;
	}

	public String getPageurl() {
		int n = getIsquote();
		if(n==1){
			return pageurl;
		}
		//防止被外链覆盖，扩展字段
		infourl="/details/"+(getAddtime().getYear()+1900)+"/"+getHtmlFileName()+".shtml";
		//判断是否有外部链接  
		if (url!=null && url.trim().length()>0) {
			pageurl=url;
		}else {
			//pageurl=(sitepath!=null?sitepath:"")+getChannelFolder()+"/info/"+(getAddtime().getYear()+1900)+"/"+getHtmlFileName()+".html";
			pageurl="/details/"+(getAddtime().getYear()+1900)+"/"+getHtmlFileName()+".shtml";	
		}
		return pageurl;
	}

	public void setPageurl(String pageurl) {
		this.pageurl = pageurl;
	}

	public String getNoids() {
		return noids;
	}

	public void setNoids(String noids) {
		this.noids = noids;
	}

	public String getDateFormat() {
		return dateFormat;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

	public String getChannelPagemark() {
		return channelPagemark;
	}

	public void setChannelPagemark(String channelPagemark) {
		this.channelPagemark = channelPagemark;
	}

	public String getSitepath() {
		return sitepath;
	}

	public void setSitepath(String sitepath) {
		this.sitepath = sitepath;
	}

	public String[] getChannels() {
		return channels;
	}

	public void setChannels(String[] channels) {
		this.channels = channels;
	}

	public Date getStarttime() {
		return starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getSearchKey() {
		return searchKey;
	}

	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey;
	}

	public String getIssign() {
		return issign;
	}

	public void setIssign(String issign) {
		this.issign = issign;
	}

	public String getVideo() {
		return video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public String getIscomment() {
		return iscomment;
	}

	public void setIscomment(String iscomment) {
		this.iscomment = iscomment;
	}

	public String getIscommentStr() {
		if (ISCOMMENT_NO.equals(iscomment)) {
			iscommentStr="否";
		}
		else if (ISCOMMENT_MEMBER.equals(iscomment)) {
			iscommentStr="会员评论";
		}
		else if (ISCOMMENT_ALL.equals(iscomment)) {
			iscommentStr="会员和匿名评论";
		}
		return iscommentStr;
	}

	public void setIscommentStr(String iscommentStr) {
		this.iscommentStr = iscommentStr;
	}

	public String getChannelParid() {
		return channelParid;
	}

	public void setChannelParid(String channelParid) {
		this.channelParid = channelParid;
	}

	public String getChannelParPagemark() {
		return channelParPagemark;
	}

	public void setChannelParPagemark(String channelParPagemark) {
		this.channelParPagemark = channelParPagemark;
	}

	public String getIndexnum() {
		return indexnum;
	}

	public void setIndexnum(String indexnum) {
		this.indexnum = indexnum;
	}

	public String getOpentype() {
		return opentype;
	}

	public void setOpentype(String opentype) {
		this.opentype = opentype;
	}

	public String getOpentimetype() {
		return opentimetype;
	}

	public void setOpentimetype(String opentimetype) {
		this.opentimetype = opentimetype;
	}

	public Date getOpenendtime() {
		return openendtime;
	}

	public void setOpenendtime(Date openendtime) {
		this.openendtime = openendtime;
	}

	public String getOpenendtimeStr() {
		if (openendtime!=null) {
			openendtimeStr=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(openendtime);
		}
		return openendtimeStr;
	}

	public void setOpenendtimeStr(String openendtimeStr) {
		this.openendtimeStr = openendtimeStr;
	}

	public List<String> getChannelids() {
		return channelids;
	}

	public void setChannelids(List<String> channelids) {
		this.channelids = channelids;
	}

	public String getCheckOpenendtime() {
		return checkOpenendtime;
	}

	public void setCheckOpenendtime(String checkOpenendtime) {
		this.checkOpenendtime = checkOpenendtime;
	}

	public String getOpenendtimeSec() {
		if (openendtime!=null) {
			openendtimeSec=(""+openendtime.getTime()).replaceAll(",", "");
		}
		return openendtimeSec;
	}

	public void setOpenendtimeSec(String openendtimeSec) {
		this.openendtimeSec = openendtimeSec;
	}

	public String getAddUserLoginName() {
		return addUserLoginName;
	}

	public void setAddUserLoginName(String addUserLoginName) {
		this.addUserLoginName = addUserLoginName;
	}

	public String getAddUserName() {
		return addUserName;
	}

	public void setAddUserName(String addUserName) {
		this.addUserName = addUserName;
	}

	public int getCountnum() {
		return countnum;
	}

	public void setCountnum(int countnum) {
		this.countnum = countnum;
	}

	public String getAdduserLike() {
		return adduserLike;
	}

	public void setAdduserLike(String adduserLike) {
		this.adduserLike = adduserLike;
	}

	public Date getInfostarttime() {
		return infostarttime;
	}

	public void setInfostarttime(Date infostarttime) {
		this.infostarttime = infostarttime;
	}

	public Date getInfoendtime() {
		return infoendtime;
	}

	public void setInfoendtime(Date infoendtime) {
		this.infoendtime = infoendtime;
	}

	public String getInfostarttimeStr() {
		if (infostarttime!=null) {
			infostarttimeStr=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(infostarttime);
		}
		return infostarttimeStr;
	}

	public void setInfostarttimeStr(String infostarttimeStr) {
		this.infostarttimeStr = infostarttimeStr;
	}

	public String getInfoendtimeStr() {
		if (infoendtime!=null) {
			infoendtimeStr=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(infoendtime);
		}
		return infoendtimeStr;
	}

	public void setInfoendtimeStr(String infoendtimeStr) {
		this.infoendtimeStr = infoendtimeStr;
	}

	public String getSitename() {
		return sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	public String getInfosite() {
		return infosite;
	}

	public void setInfosite(String infosite) {
		this.infosite = infosite;
	}

	public String getChannelname() {
		return channelname;
	}

	public void setChannelname(String channelname) {
		this.channelname = channelname;
	}

	public String getDatename() {
		return datename;
	}

	public void setDatename(String datename) {
		this.datename = datename;
	}

	public int getHtmlIndexnum() {
		return htmlIndexnum;
	}

	public void setHtmlIndexnum(int htmlIndexnum) {
		this.htmlIndexnum = htmlIndexnum;
	}

	public String getHtmlFileName() {
		if (htmlIndexnum>0) {
			htmlFileName=String.valueOf(htmlIndexnum);
		}else {
			htmlFileName=id;
		}
		return htmlFileName;
	}

	public void setHtmlFileName(String htmlFileName) {
		this.htmlFileName = htmlFileName;
	}

	public int getChannelIndexnum() {
		return channelIndexnum;
	}

	public void setChannelIndexnum(int channelIndexnum) {
		this.channelIndexnum = channelIndexnum;
	}

	public String getChannelFolder() {
		if (channelPagemark!=null && channelPagemark.trim().length()>0) {
			channelFolder=channelPagemark;
		}else if (channelIndexnum>0) {
			channelFolder=String.valueOf(channelIndexnum);
		}else {
			channelFolder=channel;
		}
		return channelFolder;
	}

	public void setChannelFolder(String channelFolder) {
		this.channelFolder = channelFolder;
	}

	public String getIshot() {
		return ishot;
	}

	public void setIshot(String ishot) {
		this.ishot = ishot;
	}

	public int getInfoStartClicknum() {
		return infoStartClicknum;
	}

	public void setInfoStartClicknum(int infoStartClicknum) {
		this.infoStartClicknum = infoStartClicknum;
	}

	public int getInfoEndClicknum() {
		return infoEndClicknum;
	}

	public void setInfoEndClicknum(int infoEndClicknum) {
		this.infoEndClicknum = infoEndClicknum;
	}

	public Date getInfostarttimeNoeq() {
		return infostarttimeNoeq;
	}

	public void setInfostarttimeNoeq(Date infostarttimeNoeq) {
		this.infostarttimeNoeq = infostarttimeNoeq;
	}

	public Date getInfoendtimeNoeq() {
		return infoendtimeNoeq;
	}

	public void setInfoendtimeNoeq(Date infoendtimeNoeq) {
		this.infoendtimeNoeq = infoendtimeNoeq;
	}

	public String getInfostarttimeNoeqStr() {
		if (infostarttimeNoeq!=null) {
			infostarttimeNoeqStr=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(infostarttimeNoeq);
		}
		return infostarttimeNoeqStr;
	}

	public void setInfostarttimeNoeqStr(String infostarttimeNoeqStr) {
		this.infostarttimeNoeqStr = infostarttimeNoeqStr;
	}

	public String getInfoendtimeNoeqStr() {
		if (infoendtimeNoeq!=null) {
			infoendtimeNoeqStr=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(infoendtimeNoeq);
		}
		return infoendtimeNoeqStr;
	}

	public void setInfoendtimeNoeqStr(String infoendtimeNoeqStr) {
		this.infoendtimeNoeqStr = infoendtimeNoeqStr;
	}

	public String getIsimgs() {
		return isimgs;
	}

	public void setIsimgs(String isimgs) {
		this.isimgs = isimgs;
	}

	public String getIsnew() {
		return isnew;
	}

	public void setIsnew(String isnew) {
		this.isnew = isnew;
	}

	public String getEditor() {
		return editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getIscheck() {
		return ischeck;
	}

	public void setIscheck(String ischeck) {
		this.ischeck = ischeck;
	}
	 public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Date getMdtime() {
		return mdtime;
	}

	public void setMdtime(Date mdtime) {
		this.mdtime = mdtime;
	}
	
	public String getIsshownewscenter() {
		return isshownewscenter;
	}

	public void setIsshownewscenter(String isshownewscenter) {
		this.isshownewscenter = isshownewscenter;
	}

	public String getIstopnewscenter() {
		return istopnewscenter;
	}

	public void setIstopnewscenter(String istopnewscenter) {
		this.istopnewscenter = istopnewscenter;
	}

	public String getIsrecommendnewscenter() {
		return isrecommendnewscenter;
	}

	public void setIsrecommendnewscenter(String isrecommendnewscenter) {
		this.isrecommendnewscenter = isrecommendnewscenter;
	}

	public String getShowtitleMark() {
		return showtitleMark;
	}

	public void setShowtitleMark(String showtitleMark) {
		this.showtitleMark = showtitleMark;
	}

	public String getAddtimeBetween() {
		return addtimeBetween;
	}

	public void setAddtimeBetween(String addtimeBetween) {
		this.addtimeBetween = addtimeBetween;
	}
	public int getIsquote() {
		return isquote;
	}

	public void setIsquote(int isquote) {
		this.isquote = isquote;
	}

	public String getQuoteinfoid() {
		return quoteinfoid;
	}

	public void setQuoteinfoid(String quoteinfoid) {
		this.quoteinfoid = quoteinfoid;
	}
		
}