package cn.freeteam.cms.model;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author limengyu
 * 内链表
 */
public class Innerlink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _innerlink.id
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _innerlink.name
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _innerlink.url
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _innerlink.addtime
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    private Date addtime;
    private String dateFormat;
    private String addtimeStr;
    /**
     * 显示的颜色
     */
	private String color;
    /**
     * 是否加粗,1为加粗，0为不加粗
     */
	private String isbold;
    
    public String getAddtimeStr() {
    	if (dateFormat==null || dateFormat.trim().length()==0) {
			dateFormat="yyyy-MM-dd HH:mm:ss";
		}
		if (addtime!=null) {
			addtimeStr=new SimpleDateFormat(dateFormat).format(addtime);
		}
		return addtimeStr;
	}

	public String getDateFormat() {
		return dateFormat;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

	public void setAddtimeStr(String addtimeStr) {
		this.addtimeStr = addtimeStr;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _innerlink.createperson
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    private String createperson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _innerlink.id
     *
     * @return the value of _innerlink.id
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _innerlink.id
     *
     * @param id the value for _innerlink.id
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _innerlink.name
     *
     * @return the value of _innerlink.name
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _innerlink.name
     *
     * @param name the value for _innerlink.name
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _innerlink.url
     *
     * @return the value of _innerlink.url
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _innerlink.url
     *
     * @param url the value for _innerlink.url
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _innerlink.addtime
     *
     * @return the value of _innerlink.addtime
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _innerlink.addtime
     *
     * @param addtime the value for _innerlink.addtime
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _innerlink.createperson
     *
     * @return the value of _innerlink.createperson
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public String getCreateperson() {
        return createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _innerlink.createperson
     *
     * @param createperson the value for _innerlink.createperson
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    public void setCreateperson(String createperson) {
        this.createperson = createperson == null ? null : createperson.trim();
    }
    public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getIsbold() {
		return isbold;
	}

	public void setIsbold(String isbold) {
		this.isbold = isbold;
	}
}