package cn.freeteam.cms.model;

import java.util.Date;

/**
 * update by liemngyu @20131213
 * 来源表
 * @author liemngyu
 */
public class Source {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_source.id
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     * 自增id
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_source.name
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     * 来源的名称
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_source.addtime
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     * 创建时间
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_source.addperson
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     * 添加人
     */
    private String addperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_source.sort
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     * 排序字段，自增
     */
    private Integer sort;
    /**
     * 引用次数
     */
    private int reference;

	public int getReference() {
		return reference;
	}

	public void setReference(int reference) {
		this.reference = reference;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_source.id
     *
     * @return the value of freecms_source.id
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_source.id
     *
     * @param id the value for freecms_source.id
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_source.name
     *
     * @return the value of freecms_source.name
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_source.name
     *
     * @param name the value for freecms_source.name
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_source.addtime
     *
     * @return the value of freecms_source.addtime
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_source.addtime
     *
     * @param addtime the value for freecms_source.addtime
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_source.addperson
     *
     * @return the value of freecms_source.addperson
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public String getAddperson() {
        return addperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_source.addperson
     *
     * @param addperson the value for freecms_source.addperson
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public void setAddperson(String addperson) {
        this.addperson = addperson == null ? null : addperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_source.sort
     *
     * @return the value of freecms_source.sort
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_source.sort
     *
     * @param sort the value for freecms_source.sort
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}