package cn.freeteam.model;

public class Dota {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_dota.id
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_dota.username
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_dota.password
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_dota.age
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_dota.id
     *
     * @return the value of freecms_dota.id
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_dota.id
     *
     * @param id the value for freecms_dota.id
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_dota.username
     *
     * @return the value of freecms_dota.username
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_dota.username
     *
     * @param username the value for freecms_dota.username
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_dota.password
     *
     * @return the value of freecms_dota.password
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_dota.password
     *
     * @param password the value for freecms_dota.password
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_dota.age
     *
     * @return the value of freecms_dota.age
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_dota.age
     *
     * @param age the value for freecms_dota.age
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}