package cn.freeteam.dao;

import cn.freeteam.model.Dota;
import cn.freeteam.model.DotaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DotaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int countByExample(DotaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int deleteByExample(DotaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int insert(Dota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int insertSelective(Dota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    List<Dota> selectByExample(DotaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    Dota selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int updateByExampleSelective(@Param("record") Dota record, @Param("example") DotaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int updateByExample(@Param("record") Dota record, @Param("example") DotaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int updateByPrimaryKeySelective(Dota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_dota
     *
     * @mbggenerated Wed Sep 25 18:33:02 CST 2013
     */
    int updateByPrimaryKey(Dota record);
}