package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.Innerlink;
import cn.freeteam.cms.model.InnerlinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnerlinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int countByExample(InnerlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int deleteByExample(InnerlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int insert(Innerlink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int insertSelective(Innerlink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    List<Innerlink> selectByExample(InnerlinkExample example);
    
    List<Innerlink> selectPageByExample(InnerlinkExample example);
    List<Innerlink> findAllInnerLink();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    Innerlink selectByPrimaryKey(Integer id);
    
    Innerlink selectByName(String name);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int updateByExampleSelective(@Param("record") Innerlink record, @Param("example") InnerlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int updateByExample(@Param("record") Innerlink record, @Param("example") InnerlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int updateByPrimaryKeySelective(Innerlink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _innerlink
     *
     * @mbggenerated Fri Dec 13 15:57:12 CST 2013
     */
    int updateByPrimaryKey(Innerlink record);
}