package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.Source;
import cn.freeteam.cms.model.SourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int countByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int deleteByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int deleteByPrimaryKey(String id);
    
    int selectByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int insertSelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    List<Source> selectByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    Source selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int updateByExample(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int updateByPrimaryKeySelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _source
     *
     * @mbggenerated Fri Dec 13 12:34:11 CST 2013
     */
    int updateByPrimaryKey(Source record);
}