package cn.freeteam.test;

public class FreecmsTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.id
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.isquote
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    private Integer isquote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.quoteinfoid
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    private String quoteinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.id
     *
     * @return the value of freecms_test.id
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.id
     *
     * @param id the value for freecms_test.id
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.isquote
     *
     * @return the value of freecms_test.isquote
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    public Integer getIsquote() {
        return isquote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.isquote
     *
     * @param isquote the value for freecms_test.isquote
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    public void setIsquote(Integer isquote) {
        this.isquote = isquote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.quoteinfoid
     *
     * @return the value of freecms_test.quoteinfoid
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    public String getQuoteinfoid() {
        return quoteinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.quoteinfoid
     *
     * @param quoteinfoid the value for freecms_test.quoteinfoid
     *
     * @mbggenerated Wed Apr 09 14:34:24 CST 2014
     */
    public void setQuoteinfoid(String quoteinfoid) {
        this.quoteinfoid = quoteinfoid == null ? null : quoteinfoid.trim();
    }
}