package com.test;

import java.util.ArrayList;
import java.util.List;

public class FreecmsTestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public FreecmsTestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBjyxIsNull() {
            addCriterion("bjyx is null");
            return (Criteria) this;
        }

        public Criteria andBjyxIsNotNull() {
            addCriterion("bjyx is not null");
            return (Criteria) this;
        }

        public Criteria andBjyxEqualTo(String value) {
            addCriterion("bjyx =", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxNotEqualTo(String value) {
            addCriterion("bjyx <>", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxGreaterThan(String value) {
            addCriterion("bjyx >", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxGreaterThanOrEqualTo(String value) {
            addCriterion("bjyx >=", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxLessThan(String value) {
            addCriterion("bjyx <", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxLessThanOrEqualTo(String value) {
            addCriterion("bjyx <=", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxLike(String value) {
            addCriterion("bjyx like", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxNotLike(String value) {
            addCriterion("bjyx not like", value, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxIn(List<String> values) {
            addCriterion("bjyx in", values, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxNotIn(List<String> values) {
            addCriterion("bjyx not in", values, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxBetween(String value1, String value2) {
            addCriterion("bjyx between", value1, value2, "bjyx");
            return (Criteria) this;
        }

        public Criteria andBjyxNotBetween(String value1, String value2) {
            addCriterion("bjyx not between", value1, value2, "bjyx");
            return (Criteria) this;
        }

        public Criteria andGzlmIsNull() {
            addCriterion("gzlm is null");
            return (Criteria) this;
        }

        public Criteria andGzlmIsNotNull() {
            addCriterion("gzlm is not null");
            return (Criteria) this;
        }

        public Criteria andGzlmEqualTo(String value) {
            addCriterion("gzlm =", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmNotEqualTo(String value) {
            addCriterion("gzlm <>", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmGreaterThan(String value) {
            addCriterion("gzlm >", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmGreaterThanOrEqualTo(String value) {
            addCriterion("gzlm >=", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmLessThan(String value) {
            addCriterion("gzlm <", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmLessThanOrEqualTo(String value) {
            addCriterion("gzlm <=", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmLike(String value) {
            addCriterion("gzlm like", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmNotLike(String value) {
            addCriterion("gzlm not like", value, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmIn(List<String> values) {
            addCriterion("gzlm in", values, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmNotIn(List<String> values) {
            addCriterion("gzlm not in", values, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmBetween(String value1, String value2) {
            addCriterion("gzlm between", value1, value2, "gzlm");
            return (Criteria) this;
        }

        public Criteria andGzlmNotBetween(String value1, String value2) {
            addCriterion("gzlm not between", value1, value2, "gzlm");
            return (Criteria) this;
        }

        public Criteria andNperIsNull() {
            addCriterion("nper is null");
            return (Criteria) this;
        }

        public Criteria andNperIsNotNull() {
            addCriterion("nper is not null");
            return (Criteria) this;
        }

        public Criteria andNperEqualTo(Integer value) {
            addCriterion("nper =", value, "nper");
            return (Criteria) this;
        }

        public Criteria andNperNotEqualTo(Integer value) {
            addCriterion("nper <>", value, "nper");
            return (Criteria) this;
        }

        public Criteria andNperGreaterThan(Integer value) {
            addCriterion("nper >", value, "nper");
            return (Criteria) this;
        }

        public Criteria andNperGreaterThanOrEqualTo(Integer value) {
            addCriterion("nper >=", value, "nper");
            return (Criteria) this;
        }

        public Criteria andNperLessThan(Integer value) {
            addCriterion("nper <", value, "nper");
            return (Criteria) this;
        }

        public Criteria andNperLessThanOrEqualTo(Integer value) {
            addCriterion("nper <=", value, "nper");
            return (Criteria) this;
        }

        public Criteria andNperIn(List<Integer> values) {
            addCriterion("nper in", values, "nper");
            return (Criteria) this;
        }

        public Criteria andNperNotIn(List<Integer> values) {
            addCriterion("nper not in", values, "nper");
            return (Criteria) this;
        }

        public Criteria andNperBetween(Integer value1, Integer value2) {
            addCriterion("nper between", value1, value2, "nper");
            return (Criteria) this;
        }

        public Criteria andNperNotBetween(Integer value1, Integer value2) {
            addCriterion("nper not between", value1, value2, "nper");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table freecms_test
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 02 17:37:45 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table freecms_test
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}