package com.test;

public class FreecmsTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.id
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.bjyx
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    private String bjyx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.gzlm
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    private String gzlm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_test.nper
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    private Integer nper;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.id
     *
     * @return the value of freecms_test.id
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.id
     *
     * @param id the value for freecms_test.id
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.bjyx
     *
     * @return the value of freecms_test.bjyx
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public String getBjyx() {
        return bjyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.bjyx
     *
     * @param bjyx the value for freecms_test.bjyx
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void setBjyx(String bjyx) {
        this.bjyx = bjyx == null ? null : bjyx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.gzlm
     *
     * @return the value of freecms_test.gzlm
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public String getGzlm() {
        return gzlm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.gzlm
     *
     * @param gzlm the value for freecms_test.gzlm
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void setGzlm(String gzlm) {
        this.gzlm = gzlm == null ? null : gzlm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_test.nper
     *
     * @return the value of freecms_test.nper
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public Integer getNper() {
        return nper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_test.nper
     *
     * @param nper the value for freecms_test.nper
     *
     * @mbggenerated Mon Dec 02 17:37:45 CST 2013
     */
    public void setNper(Integer nper) {
        this.nper = nper;
    }
}